### YamlMime:ManagedReference
items:
- uid: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema
  commentId: T:NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema
  id: ModuleConfigSchema
  parent: NeonSuit.RSSReader.Core.Modules
  children:
  - NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
  langs:
  - csharp
  - vb
  name: ModuleConfigSchema
  nameWithType: ModuleConfigSchema
  fullName: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema
  type: Class
  source:
    remote:
      path: src/Core/NeonSuit.RSSReader.Core/Interfaces/Modules/IConfigurableModule.cs
      branch: master
      repo: https://github.com/NidroySoft/NeonSuit.RSSReader.git
    id: ModuleConfigSchema
    path: ../src/Core/NeonSuit.RSSReader.Core/Interfaces/Modules/IConfigurableModule.cs
    startLine: 40
  assemblies:
  - NeonSuit.RSSReader.Core
  namespace: NeonSuit.RSSReader.Core.Modules
  summary: Module configuration schema.
  example: []
  syntax:
    content: public class ModuleConfigSchema
    content.vb: Public Class ModuleConfigSchema
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
  commentId: P:NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
  id: Properties
  parent: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: ModuleConfigSchema.Properties
  fullName: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
  type: Property
  source:
    remote:
      path: src/Core/NeonSuit.RSSReader.Core/Interfaces/Modules/IConfigurableModule.cs
      branch: master
      repo: https://github.com/NidroySoft/NeonSuit.RSSReader.git
    id: Properties
    path: ../src/Core/NeonSuit.RSSReader.Core/Interfaces/Modules/IConfigurableModule.cs
    startLine: 45
  assemblies:
  - NeonSuit.RSSReader.Core
  namespace: NeonSuit.RSSReader.Core.Modules
  summary: Gets or sets the configuration properties.
  example: []
  syntax:
    content: public Dictionary<string, ModuleConfigProperty> Properties { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty}
    content.vb: Public Property Properties As Dictionary(Of String, ModuleConfigProperty)
  overload: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties*
references:
- uid: NeonSuit.RSSReader.Core.Modules
  commentId: N:NeonSuit.RSSReader.Core.Modules
  href: NeonSuit.html
  name: NeonSuit.RSSReader.Core.Modules
  nameWithType: NeonSuit.RSSReader.Core.Modules
  fullName: NeonSuit.RSSReader.Core.Modules
  spec.csharp:
  - uid: NeonSuit
    name: NeonSuit
    href: NeonSuit.html
  - name: .
  - uid: NeonSuit.RSSReader
    name: RSSReader
    href: NeonSuit.RSSReader.html
  - name: .
  - uid: NeonSuit.RSSReader.Core
    name: Core
    href: NeonSuit.RSSReader.Core.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.Modules
    name: Modules
    href: NeonSuit.RSSReader.Core.Modules.html
  spec.vb:
  - uid: NeonSuit
    name: NeonSuit
    href: NeonSuit.html
  - name: .
  - uid: NeonSuit.RSSReader
    name: RSSReader
    href: NeonSuit.RSSReader.html
  - name: .
  - uid: NeonSuit.RSSReader.Core
    name: Core
    href: NeonSuit.RSSReader.Core.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.Modules
    name: Modules
    href: NeonSuit.RSSReader.Core.Modules.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties*
  commentId: Overload:NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
  href: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.html#NeonSuit_RSSReader_Core_Modules_ModuleConfigSchema_Properties
  name: Properties
  nameWithType: ModuleConfigSchema.Properties
  fullName: NeonSuit.RSSReader.Core.Modules.ModuleConfigSchema.Properties
- uid: System.Collections.Generic.Dictionary{System.String,NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty}
  commentId: T:System.Collections.Generic.Dictionary{System.String,NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, ModuleConfigProperty>
  nameWithType: Dictionary<string, ModuleConfigProperty>
  fullName: System.Collections.Generic.Dictionary<string, NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty>
  nameWithType.vb: Dictionary(Of String, ModuleConfigProperty)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty)
  name.vb: Dictionary(Of String, ModuleConfigProperty)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty
    name: ModuleConfigProperty
    href: NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty
    name: ModuleConfigProperty
    href: NeonSuit.RSSReader.Core.Modules.ModuleConfigProperty.html
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
