### YamlMime:ManagedReference
items:
- uid: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto
  commentId: T:NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto
  id: UpdateModuleConfigDto
  parent: NeonSuit.RSSReader.Core.DTOs.Modules
  children:
  - NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
  - NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
  langs:
  - csharp
  - vb
  name: UpdateModuleConfigDto
  nameWithType: UpdateModuleConfigDto
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto
  type: Class
  source:
    remote:
      path: src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
      branch: master
      repo: https://github.com/NidroySoft/NeonSuit.RSSReader.git
    id: UpdateModuleConfigDto
    path: ../src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
    startLine: 8
  assemblies:
  - NeonSuit.RSSReader.Core
  namespace: NeonSuit.RSSReader.Core.DTOs.Modules
  summary: Data Transfer Object for updating module configuration.
  example: []
  syntax:
    content: public class UpdateModuleConfigDto
    content.vb: Public Class UpdateModuleConfigDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
  commentId: P:NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
  id: ModuleId
  parent: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto
  langs:
  - csharp
  - vb
  name: ModuleId
  nameWithType: UpdateModuleConfigDto.ModuleId
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
  type: Property
  source:
    remote:
      path: src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
      branch: master
      repo: https://github.com/NidroySoft/NeonSuit.RSSReader.git
    id: ModuleId
    path: ../src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
    startLine: 13
  assemblies:
  - NeonSuit.RSSReader.Core
  namespace: NeonSuit.RSSReader.Core.DTOs.Modules
  summary: Module ID.
  example: []
  syntax:
    content: >-
      [Required]

      public string ModuleId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property ModuleId As String
  overload: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
  commentId: P:NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
  id: Config
  parent: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: UpdateModuleConfigDto.Config
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
  type: Property
  source:
    remote:
      path: src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
      branch: master
      repo: https://github.com/NidroySoft/NeonSuit.RSSReader.git
    id: Config
    path: ../src/Core/NeonSuit.RSSReader.Core/DTOs/Modules/UpdateModuleConfigDto.cs
    startLine: 19
  assemblies:
  - NeonSuit.RSSReader.Core
  namespace: NeonSuit.RSSReader.Core.DTOs.Modules
  summary: Configuration values.
  example: []
  syntax:
    content: public Dictionary<string, object> Config { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Object}
    content.vb: Public Property Config As Dictionary(Of String, Object)
  overload: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config*
references:
- uid: NeonSuit.RSSReader.Core.DTOs.Modules
  commentId: N:NeonSuit.RSSReader.Core.DTOs.Modules
  href: NeonSuit.html
  name: NeonSuit.RSSReader.Core.DTOs.Modules
  nameWithType: NeonSuit.RSSReader.Core.DTOs.Modules
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules
  spec.csharp:
  - uid: NeonSuit
    name: NeonSuit
    href: NeonSuit.html
  - name: .
  - uid: NeonSuit.RSSReader
    name: RSSReader
    href: NeonSuit.RSSReader.html
  - name: .
  - uid: NeonSuit.RSSReader.Core
    name: Core
    href: NeonSuit.RSSReader.Core.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.DTOs
    name: DTOs
    href: NeonSuit.RSSReader.Core.DTOs.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.DTOs.Modules
    name: Modules
    href: NeonSuit.RSSReader.Core.DTOs.Modules.html
  spec.vb:
  - uid: NeonSuit
    name: NeonSuit
    href: NeonSuit.html
  - name: .
  - uid: NeonSuit.RSSReader
    name: RSSReader
    href: NeonSuit.RSSReader.html
  - name: .
  - uid: NeonSuit.RSSReader.Core
    name: Core
    href: NeonSuit.RSSReader.Core.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.DTOs
    name: DTOs
    href: NeonSuit.RSSReader.Core.DTOs.html
  - name: .
  - uid: NeonSuit.RSSReader.Core.DTOs.Modules
    name: Modules
    href: NeonSuit.RSSReader.Core.DTOs.Modules.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId*
  commentId: Overload:NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
  href: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.html#NeonSuit_RSSReader_Core_DTOs_Modules_UpdateModuleConfigDto_ModuleId
  name: ModuleId
  nameWithType: UpdateModuleConfigDto.ModuleId
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.ModuleId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config*
  commentId: Overload:NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
  href: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.html#NeonSuit_RSSReader_Core_DTOs_Modules_UpdateModuleConfigDto_Config
  name: Config
  nameWithType: UpdateModuleConfigDto.Config
  fullName: NeonSuit.RSSReader.Core.DTOs.Modules.UpdateModuleConfigDto.Config
- uid: System.Collections.Generic.Dictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, object>
  nameWithType: Dictionary<string, object>
  fullName: System.Collections.Generic.Dictionary<string, object>
  nameWithType.vb: Dictionary(Of String, Object)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, Object)
  name.vb: Dictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
